name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

permissions:
    contents: read
    packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        
      - name: Build Docker image
        run: ./build.sh

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker tag fabrika-troliv:${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository }}/fabrika-troliv:${{ env.IMAGE_TAG }}
          docker push ghcr.io/${{ github.repository }}/fabrika-troliv:${{ env.IMAGE_TAG }}

      - name: Clean up old images
        run: |
          docker image prune -f