name: Deploy to VPS

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v3

      - name: Transfer .env file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env"
          target: "~/fabrika-troliv/.env"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop and remove any running container
            docker stop fabrika-troliv || true
            docker rm fabrika-troliv || true

            # Pull the new image from GitHub Container Registry
            docker pull ghcr.io/${{ github.repository }}/fabrika-troliv:${{ env.IMAGE_TAG }}

            # Run the new container with the .env file
            docker run -d --name fabrika-troliv --env-file ~/fabrika-troliv/.env ghcr.io/${{ github.repository }}/fabrika-troliv:${{ env.IMAGE_TAG }}
